name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx webpack --mode production
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b gh-pages-temp
          mv ./dist/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages-temp:gh-pages --force
          git checkout main
          git branch -D gh-pages-temp
        with:
          github_token: ${{ secrets.MOSAICA_TOKEN }}
          publish_dir: ./